language: python

virtualenv:
  system_site_packages: true

sudo: required

env: PLUGIN=metadata

services:
  - docker

before_install:
  - git clone --recurse-submodules git://github.com/sbesson/omero-test-infra -b cli_pycheck .omero

script:
  - .omero/cli-docker
