language: python

virtualenv:
  system_site_packages: true

sudo: required

env: PLUGIN=metadata

services:
  - docker

before_install:
  - git clone git://github.com/sbesson/omero-test-infra -b PLUGIN_envvar .omero

script:
  - .omero/cli-docker
